#!/usr/bin/env python3
"""Bundles the modular sources into ONE self-contained .mq5.

    python3 tools/build_single_file.py            # build
    python3 tools/build_single_file.py --check    # fail if the bundle is stale

Why both layouts exist: the modular files are the source of truth because they
are far easier to review and to test in isolation. The bundle is the artefact
you install, because a folder of headers that must stay in step is exactly the
fragility that produced forty misleading compile errors when one header was
copied and another was not. Generating one from the other means they cannot
disagree, and audit_static.py fails the build if the bundle is out of date.
"""
import os, re, sys, hashlib

ROOT = 'MQL5/Experts/XAUUSD_FTMO'
OUT  = 'MQL5/Experts/XAUUSD_FTMO_Confluence_EA.mq5'
EA   = f'{ROOT}/XAUUSD_FTMO_Confluence_EA.mq5'

# dependency order - CoreDefs first, everything else depends on it
ORDER = ['CoreDefs.mqh', 'TimeZones.mqh', 'NewsFilter.mqh', 'RiskGuard.mqh',
         'ConfluenceEngine.mqh', 'TradeExecutor.mqh', 'Statistics.mqh', 'Dashboard.mqh']

def strip_header(text, name):
    """Remove include guards, project #includes and the version stamp block."""
    out = []
    for line in text.split('\n'):
        st = line.strip()
        if st.startswith('#include "'):            # project header - inlined already
            continue
        if re.match(r'^#(ifndef|define|endif)\s+__XAUUSD_FTMO_\w+__', st):
            continue
        if st == '#endif' and out and out[-1].strip().startswith('//---'):
            continue
        if re.match(r'^#define\s+XFC_V_\w+', st):  # stamps are meaningless in a bundle
            continue
        if st.startswith('#property'):
            # #property must sit at the top of the file; the EA's own preamble
            # already carries them, and a second copy mid-file is a compile error
            continue
        out.append(line)
    body = '\n'.join(out)
    # trailing include-guard #endif, if it survived
    body = re.sub(r'\n#endif\s*//\s*__XAUUSD_FTMO_\w+__\s*\n', '\n', body)
    banner = ('\n//==================================================================\n'
              f'//  {name}\n'
              '//==================================================================\n')
    return banner + body.strip('\n') + '\n'

def build():
    ea = open(EA).read()

    # the EA's own preamble: everything up to the first project include
    m = re.search(r'^#include "Include/', ea, re.M)
    preamble = ea[:m.start()]
    rest = ea[m.start():]
    # drop the include block and the version-stamp checks (single file = no stamps)
    rest = re.sub(r'^#include "Include/[^"]+"\n', '', rest, flags=re.M)
    rest = re.sub(r'\n//\+-+\+\n//\| INCLUDE VERSION CHECK.*?(?=\n//\+-+\+\n//\| INPUTS)',
                  '\n', rest, flags=re.S)
    rest = re.sub(r'#ifndef XFC_V_\w+\n\s+int STALE_INCLUDE__\w+ = \w+;\n#endif\n', '', rest)

    parts = [preamble.rstrip('\n')]
    parts.append('''
//+------------------------------------------------------------------+
//| SINGLE-FILE BUILD                                                |
//|                                                                  |
//| Generated by tools/build_single_file.py from the modular sources |
//| under MQL5/Experts/XAUUSD_FTMO/. Do not edit this file directly  |
//| - edit the module and rebuild, or your change is lost on the     |
//| next generation.                                                 |
//|                                                                  |
//| It has NO includes at all: not the project headers, and not the  |
//| MQL5 Standard Library either. Order handling is implemented      |
//| directly on OrderSend() in CRawTrade/CRawPosition below. Drop    |
//| this one file into MQL5/Experts and compile.                     |
//+------------------------------------------------------------------+''')

    for name in ORDER:
        parts.append(strip_header(open(f'{ROOT}/Include/{name}').read(), name))

    parts.append('\n//==================================================================\n'
                 '//  EXPERT ADVISOR\n'
                 '//==================================================================\n')
    parts.append(rest.strip('\n'))
    return '\n'.join(parts) + '\n'

text = build()

# Stamp the build with a hash of its own content. Bumping a version string by
# hand is a step that gets forgotten - it was, and the diagnostics file then
# reported the same build id before and after a change, so there was no way to
# tell a stale binary from a new one. Deriving it from the source cannot be
# forgotten: any change to any module changes the stamp.
import re as _re
_placeholder = '#define XFC_BUILD_ID "dev"'
_body = text.replace(_placeholder, '#define XFC_BUILD_ID "<stamp>"')
_stamp = hashlib.sha256(_body.encode()).hexdigest()[:8]
text = text.replace(_placeholder, f'#define XFC_BUILD_ID "{_stamp}"')

if '--check' in sys.argv:
    cur = open(OUT).read() if os.path.exists(OUT) else None
    if cur != text:
        print(f"STALE: {OUT} does not match the modular sources")
        print("Run: python3 tools/build_single_file.py")
        sys.exit(1)
    print(f"{OUT} is up to date")
    sys.exit(0)

open(OUT, 'w').write(text)
n = len(text.split('\n'))
print(f"built {OUT}")
print(f"  {n:,} lines, {len(text)/1024:.0f} KB")
print(f"  includes: {len(re.findall(r'^#include', text, re.M))}")
print(f"  build id: {_stamp}   <- must match run,build_id in XFC_diag*.csv")
