#!/usr/bin/env python3
"""Amalgamate the SMC AI Agent into one self-contained .mq5 file.

The multi-file layout is the maintainable one, but it requires the .mqh
files to sit in <MT5 data folder>/MQL5/Include/SMCAgent/. This produces a
single file that can be dropped anywhere and compiled with no includes.

Run from the repository root:  python3 tools/build_single_file.py
"""
import re, pathlib, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC  = ROOT / "MQL5" / "Experts" / "SMCAgent" / "SMC_AI_Agent.mq5"
INC  = ROOT / "MQL5" / "Include" / "SMCAgent"
OUT  = ROOT / "MQL5" / "Experts" / "SMCAgent" / "SMC_AI_Agent_SingleFile.mq5"

# dependency order - every file appears after everything it needs
ORDER = ["Defs.mqh", "TimeZones.mqh", "Logger.mqh", "MarketState.mqh",
         "SmcEngine.mqh", "NewsFilter.mqh", "Learner.mqh", "RiskManager.mqh",
         "Confluence.mqh", "TradeManager.mqh", "Visuals.mqh"]

ea = SRC.read_text()
lines = ea.split("\n")

first = next(i for i, l in enumerate(lines) if l.startswith("#include <SMCAgent/"))
last  = max(i for i, l in enumerate(lines) if l.startswith("#include <SMCAgent/"))
header, body = lines[:first], lines[last + 1:]

parts = [
    "\n".join(header).rstrip(),
    "",
    "//" + "=" * 66,
    "//  SINGLE FILE BUILD - generated by tools/build_single_file.py",
    "//  Generated %s from the modular sources in MQL5/Include/SMCAgent/." % datetime.date.today(),
    "//  Edit the modular sources, then regenerate. Do not edit this file.",
    "//" + "=" * 66,
    "",
    "#include <Trade/Trade.mqh>",
    "",
]

for name in ORDER:
    text = (INC / name).read_text()
    # drop local includes; the content is inlined in dependency order
    text = re.sub(r'^\s*#include\s+"[^"]+"\s*$', "", text, flags=re.M)
    text = re.sub(r'^\s*#include\s+<Trade/Trade\.mqh>\s*$', "", text, flags=re.M)
    parts += ["//" + "-" * 66,
              "//  %s" % name,
              "//" + "-" * 66,
              text.rstrip(), ""]

parts += ["//" + "=" * 66,
          "//  Expert body",
          "//" + "=" * 66,
          "\n".join(body).lstrip("\n")]

OUT.write_text("\n".join(parts))

txt = OUT.read_text()
print("wrote %s" % OUT.relative_to(ROOT))
print("  lines            : %d" % txt.count("\n"))
print("  local includes   : %d (must be 0)" % len(re.findall(r'#include\s+"', txt)))
print("  library includes : %s" % re.findall(r'#include\s+<[^>]+>', txt))
print("  include guards   : %d ifndef / %d endif" % (txt.count("#ifndef"), txt.count("#endif")))
